spring:
  datasource:
    url: jdbc:mysql://localhost:3306/athena?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

server:
  port: 8000

logging:
  config: classpath:logback-spring.xml
  level: debug